---
title: "R Notebook"
output: html_notebook
---

Phylogenetic tree of just methylotrophs

```{r}
library(phyloseq)
library(picante)
library(tidyverse)
library(vegan)

```

```{r}
# load in edited taxa table with only the ASVs that I want
methylotroph_taxa_table <- read.table("methylotroph_ASV_counts.csv", header = T, sep = ",")

# load in full taxa table with all recovered ASV taxa
bact_taxa_table <- as.matrix(read.table("June_Oct_MERGE_ASV_taxa_table.tsv", header = T, row.names = 1, check.names = F, sep = "\t"))

# load in full count table with all ASVs recovered
bact_count_table <- read.table("June_Oct_MERGE_ASV_counts.csv", header = T, check.names = F, sep = ",") 

# sort full count table and only keep only the ASVs that are in the methylotroph taxa table 
methylotroph_count_table <- bact_count_table[(bact_count_table$ASV_name %in% methylotroph_taxa_table$x),]

# make ASVs the row names for table
methylotroph_count_table <- methylotroph_count_table %>% remove_rownames %>% column_to_rownames(var="ASV_name")

methylotroph_taxa_table <- methylotroph_taxa_table %>% remove_rownames %>% column_to_rownames(var="x") %>% as.data.frame() %>% as.matrix()

# load in metadata table
bact_sample_info_table <- read.table("June_Oct_16S_MERGE_metadata - Copy.csv", header = T, row.names = 1, sep = ",")

# assign phyloseq object types to tables
M_count_tab_phy <- otu_table(methylotroph_count_table, taxa_are_rows=T)
M_tax_tab_phy <- phyloseq::tax_table(methylotroph_taxa_table)

# make phyloseq object
ASV_physeq_M <- phyloseq(M_count_tab_phy, M_tax_tab_phy, bact_sample_info_table)
```

```{r}
# make a phylogenetic tree
ASV_tree_M = rtree(ntaxa(ASV_physeq_M), rooted=TRUE, tip.label=taxa_names(ASV_physeq_M))

str(ASV_tree_M)

class(ASV_tree_M)

Ntip(ASV_tree_M)
```

```{r}
# plot our phylogeny (the cex argument makes the labels small enough to read)
plot(ASV_tree_M, cex = 0.5)
```

this isn't very helpful since the tips are in ASVs, rather than the taxonomic names. I'm going to try to make it so the family and genus are shown

```{r}
paste(df$n,df$s,sep="-")

# making a vector of family names
family <- as.vector(methylotroph_taxa_table[,"Family"])

ASV_tree_M = rtree(ntaxa(ASV_physeq_M), rooted=TRUE, tip.label=family)

str(ASV_tree_M)

class(ASV_tree_M)

Ntip(ASV_tree_M)

plot(ASV_tree_M, cex = 0.5)

plot(unroot(ASV_tree_M),type="unrooted",no.margin=TRUE,lab4ut="axial",
    edge.width=2)
```

Ok cool and all but this only takes into account the ASV counts, but I want to actually look at the phylogenies using the recovered sequences, which is a whole other thing.
